### ISSUE TITLE
Syndrome-Error-Decoding

### ISSUE THREAD

**Issue by bansharai** [AmeanAsad/Syndrome-Error-Decoding#1]
Hello sir,
      I tried to run the program it shows no error but the simulation result is not showing anything

**Comment by AmeanAsad** [comment]
@bansharai I added a commit to reference this issue: https://github.com/AmeanAsad/Syndrome-Error-Decoding/commit/029f1c6101e5cf91884745359e9e3cf71ed2a366

**Comment by AmeanAsad** [comment]
Added a commented line to be able to run the demonstrated plots: https://github.com/AmeanAsad/Syndrome-Error-Decoding/blob/029f1c6101e5cf91884745359e9e3cf71ed2a366/decoding_simulation.py#L176

You can run the output by calling the function `visualization` in the file `decoding_simulation.py`

**Comment by AmeanAsad** [comment]
Closing as confirmed with @bansharai implementation is working after most recent commit.
